name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hi Haitham"
      - name: multiline script
        run: |
          node -v
          npm -v
  windows-commands:
    runs-on: windows-latest
    steps:
      - name: path of directory
        run: Get-Location
  second-windows-commands:
    runs-on: windows-latest
    needs: [windows-commands]
    steps:
      - name: path of directory pwd
        run: pwd
        shell: bash
