name: shell commands

on:
  push:
    tags:
      - merge-to-master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hiii Haitham"
      - name: multiline script
        run: |
          node -v
          npm -v
  windows-commands:
    runs-on: windows-latest
    steps:
      - name: path of directory
        run: Get-Location
  second-windows-commands:
    runs-on: windows-latest
    needs: [windows-commands]
    steps:
      - name: path of directory pwd
        run: pwd
        shell: bash
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: javascript actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Haitham
      - name: log greeting
        run: echo "${{ steps.greet.outputs.time }}"
